import './styles.css'
import { supabase } from './lib/supabase.js'
import standings from './standings.json'
import players from './players.json'

const app = document.querySelector('#app')
let session = null
let profile = null
let matches = []
const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const canEdit = () => profile?.role === 'editor'

function renderAuth(){app.innerHTML=`<main class="auth-shell"><section class="auth-card"><div class="crest">FF</div><p class="eyebrow">Football Fanatics</p><h1>Team hub</h1><p class="muted">Sign in to view the match record. Editors can update it.</p><form id="auth-form"><input id="email" type="email" placeholder="Email" required><input id="password" type="password" placeholder="Password" required><button class="primary">Sign in</button><p id="auth-message" class="message"></p></form></section></main>`;document.querySelector('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:email.value,password:password.value});document.querySelector('#auth-message').textContent=error?error.message:'Signed in.'})}
function renderApp(){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="crest">FF</div><div><strong>Football Fanatics</strong><small>team hub</small></div></div><nav><button data-page="dashboard" class="active">Dashboard</button><button data-page="matches">Matches</button><button data-page="players">Players</button></nav><div class="side-foot"><span>${esc(session.user.email)}</span><b>${canEdit()?'Editor':'Viewer'}</b><button id="signout" class="ghost">Sign out</button></div></aside><main class="main"><header><div><span class="eyebrow">Authenticated workspace</span><h1 id="page-title">Dashboard</h1></div><span class="role">${canEdit()?'EDIT ACCESS':'VIEW ONLY'}</span></header><section id="content"></section></main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelector('#signout').addEventListener('click',()=>supabase.auth.signOut());showPage('dashboard')}
async function loadMatches(){const{data,error}=await supabase.from('matches').select('*').order('match_date',{ascending:false});matches=error?[]:data}
function standingsTable(season){const rows=standings[season]||[];return `<section class="standings-section"><div class="section-head"><div><h2>League table</h2><p class="muted">Played, W/D/L, goals and points</p></div><select id="standing-season"><option value="2025-2026" ${season==='2025-2026'?'selected':''}>2025-2026</option><option value="2024-2025" ${season==='2024-2025'?'selected':''}>2024-2025</option></select></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>Pts</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.team==='Football Fanatics'?'highlight':''}"><td>${r.rank}</td><td>${esc(r.team)}</td><td>${r.played}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.for}</td><td>${r.against}</td><td>${r.gd>0?'+':''}${r.gd}</td><td><strong>${r.points}</strong></td></tr>`).join('')}</tbody></table></div></section>`}
function playersTable(){const rows=[...players].sort((a,b)=>b.totalGoals-a.totalGoals||b.leagueApps-a.leagueApps);return `<section class="players-section"><div class="section-head"><div><h2>Players</h2><p class="muted">League and cup participation, goals and total goals</p></div><span class="role">${rows.length} players</span></div><div class="table-wrap"><table><thead><tr><th>Player</th><th>League apps</th><th>Cup apps</th><th>League goals</th><th>Cup goals</th><th>Total goals</th></tr></thead><tbody>${rows.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${p.leagueApps}</td><td>${p.cupApps}</td><td>${p.leagueGoals}</td><td>${p.cupGoals}</td><td><strong>${p.totalGoals}</strong></td></tr>`).join('')}</tbody></table></div></section>`}
function showPage(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelector('#page-title').textContent=page==='dashboard'?'Season overview':page==='players'?'Players':'Match centre';const content=document.querySelector('#content');if(page==='dashboard'){content.innerHTML=`<section class="hero"><div><h2>View the record with the right permissions.</h2><p class="muted">${matches.length} matches loaded from Supabase. ${canEdit()?'You can edit the shared record.':'Your access is read-only.'}</p></div><div class="metric"><strong>${matches.length}</strong><span>recorded matches</span></div></section><div class="notice">${canEdit()?'Editor mode is on.':'Viewer mode is on.'}</div>${standingsTable('2025-2026')}`;bindStanding()}else if(page==='players'){content.innerHTML=playersTable()}else{content.innerHTML=`<section class="toolbar"><p class="muted">${matches.length} shared matches</p>${canEdit()?'<button id="add-match" class="primary">Add match</button>':''}</section><div class="table-wrap"><table><thead><tr><th>Date</th><th>Opponent</th><th>Competition</th><th>Score</th><th>Result</th>${canEdit()?'<th></th>':''}</tr></thead><tbody>${matches.map(m=>`<tr><td>${esc(m.match_date)}</td><td>${esc(m.opponent)}</td><td>${esc(m.competition)}</td><td>${esc(m.score||'vs')}</td><td>${esc(m.result||'Upcoming')}</td>${canEdit()?`<td><button class="edit" data-id="${m.id}">Edit</button></td>`:''}</tr>`).join('')}</tbody></table></div>`;if(canEdit()){document.querySelector('#add-match').addEventListener('click',()=>openEditor());document.querySelectorAll('.edit').forEach(b=>b.addEventListener('click',()=>openEditor(matches.find(m=>String(m.id)===b.dataset.id))))}}}
function bindStanding(){document.querySelector('#standing-season')?.addEventListener('change',e=>{document.querySelector('.standings-section').outerHTML=standingsTable(e.target.value);bindStanding()})}
function openEditor(match={}){const edit=Boolean(match.id),d=document.createElement('dialog');d.innerHTML=`<form method="dialog" class="dialog-card"><h2>${edit?'Edit match':'Add match'}</h2><input id="m-date" type="date" value="${match.match_date||''}" required><input id="m-opponent" placeholder="Opponent" value="${esc(match.opponent||'')}" required><select id="m-comp"><option ${match.competition==='League'?'selected':''}>League</option><option ${match.competition==='Cup'?'selected':''}>Cup</option></select><input id="m-score" placeholder="Score, e.g. 2-1" value="${esc(match.score||'')}"><input id="m-result" placeholder="Result, e.g. W, D, L" value="${esc(match.result||'')}"><textarea id="m-notes" placeholder="Scorers and notes">${esc(match.notes||'')}</textarea><div class="dialog-actions"><button value="cancel" class="ghost">Cancel</button><button id="save" value="default" class="primary">Save</button></div></form>`;document.body.append(d);d.showModal();d.querySelector('#save').addEventListener('click',async e=>{e.preventDefault();const p={match_date:d.querySelector('#m-date').value,opponent:d.querySelector('#m-opponent').value,competition:d.querySelector('#m-comp').value,score:d.querySelector('#m-score').value,result:d.querySelector('#m-result').value,notes:d.querySelector('#m-notes').value};const req=edit?supabase.from('matches').update(p).eq('id',match.id):supabase.from('matches').insert(p);const{error}=await req;if(error){alert(error.message);return}d.close();d.remove();await loadMatches();showPage('matches')})}
async function boot(){const{data}=await supabase.auth.getSession();session=data.session;if(!session){renderAuth();return}const{data:p}=await supabase.from('profiles').select('role').eq('id',session.user.id).single();profile=p||{role:'viewer'};await loadMatches();renderApp()}
supabase.auth.onAuthStateChange((_e,next)=>{session=next;if(next)boot();else renderAuth()});boot()
