import './styles.css'
import { supabase } from './lib/supabase.js'
import staticPlayers from './players.json'
import staticPlayerMatches from './player_matches.json'
import standings from './standings.json'

const app=document.querySelector('#app');let session=null,profile=null,matches=[],players=[],playerMatches=[],customSeasons=[]
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canEdit=()=>profile?.role==='editor';const rc=r=>r==='W'?'win':r==='D'?'draw':r==='L'?'loss':'upcoming';
const idFor=name=>String(name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function renderAuth(){app.innerHTML=`<main class="auth-shell"><section class="auth-card"><div class="crest">FF</div><p class="eyebrow">Football Fanatics</p><h1>Team hub</h1><p class="muted">Sign in to view the match record. Editors can update it.</p><form id="auth-form"><input id="email" type="email" placeholder="Email" required><input id="password" type="password" placeholder="Password" required><button class="primary">Sign in</button><p id="auth-message" class="message"></p></form></section></main>`;document.querySelector('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:email.value,password:password.value});document.querySelector('#auth-message').textContent=error?error.message:'Signed in.'})}
async function load(){const [m,p,pm,s]=await Promise.all([supabase.from('matches').select('*').order('match_date',{ascending:false}),supabase.from('players').select('*').order('name'),supabase.from('player_match_stats').select('*').order('match_date',{ascending:false}),supabase.from('seasons').select('*').order('season')]);matches=m.data||[];players=p.data?.length?p.data:staticPlayers.map(x=>({...x,id:x.id,jersey_number:x.jerseyNumber,league_apps:x.leagueApps,league_goals:x.leagueGoals,cup_apps:x.cupApps,cup_goals:x.cupGoals,total_goals:x.totalGoals}));playerMatches=pm.data?.length?pm.data:staticPlayerMatches;customSeasons=s.data||[]}
function shell(){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="crest">FF</div><div><strong>Football Fanatics</strong><small>team hub</small></div></div><nav><button data-page="dashboard" class="active">Tablazat</button><button data-page="matches">Merkozesek</button><button data-page="players">Jatekosok</button></nav><div class="side-foot"><span>${esc(session.user.email)}</span><b>${canEdit()?'Editor':'Viewer'}</b><button id="signout" class="ghost">Sign out</button></div></aside><main class="main"><header><div><span class="eyebrow">Authenticated workspace</span><h1 id="page-title">Tablazat</h1></div><span class="role">${canEdit()?'EDIT ACCESS':'VIEW ONLY'}</span></header><section id="content"></section></main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));document.querySelector('#signout').addEventListener('click',()=>supabase.auth.signOut());show('dashboard')}
function seasonNames(){return [...new Set([...Object.keys(standings),...customSeasons.map(s=>s.season)])].sort().reverse()}
function teamTable(season){const rows=standings[season]||[];if(!rows.length)return `<div class="empty"><strong>Nincs tabella ehhez a szezonhoz</strong>Adj hozza csapatokat vagy meccseket kesobb.</div>`;return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Csapat</th><th>J</th><th>Gy</th><th>D</th><th>V</th><th>RG</th><th>KG</th><th>GA</th><th>Pont</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.team==='Football Fanatics'?'highlight':''}"><td>${r.rank}</td><td><strong>${esc(r.team)}</strong></td><td>${r.played}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd>0?'+':''}${r.gd}</td><td><strong>${r.points}</strong></td></tr>`).join('')}</tbody></table></div>`}
function seasonPlayers(season){
 const ids=new Set([...playerSeasons.filter(x=>x.season===season).map(x=>x.player_id),...playerMatches.filter(x=>x.season===season).map(x=>x.player_id||x.playerId)]);
 const rows=players.filter(p=>ids.has(p.id));
 if(!rows.length)return '<div class="empty"><strong>Nincs jatekos ehhez a szezonhoz</strong>A Jatekos hozzaadasa gombbal felvehetsz egyet.</div>';
 return '<div class="season-player-list">'+rows.map(p=>'<button class="season-player" data-season-player="'+esc(p.id)+'"><span class="player-number">'+(p.jersey_number??p.jerseyNumber??'')+'</span><span><strong>'+esc(p.name)+'</strong><small>'+((p.league_apps??p.leagueApps??0)+(p.cup_apps??p.cupApps??0))+' Jatszott · '+(p.total_goals??p.totalGoals??0)+' Gol</small></span><span aria-hidden="true">↗</span></button>').join('')+'</div>';
}
function bindSeasonPlayers(){document.querySelectorAll('[data-season-player]').forEach(b=>b.addEventListener('click',()=>openPlayerProfile(b.dataset.seasonPlayer)));}
function dashboard(){let seasons=seasonNames(),selected=seasons.includes('2025-2026')?'2025-2026':seasons[0];return `<section class="hero"><div><h2>Szezon attekintese</h2><p class="muted">${matches.length} shared matches. ${canEdit()?'Editor mode is on.':'Your access is read-only.'}</p></div><div class="metric"><strong>${matches.length}</strong><span>recorded matches</span></div></section><section class="panel"><div class="section-head"><div><h2>Tablazat</h2><p class="muted">Minden csapat, J / Gy / D / V, golok es pontok</p></div><div class="profile-actions">${canEdit()?'<button class="primary" id="add-season">Uj szezon</button>':''}<select id="team-season">${seasons.map(s=>`<option value="${esc(s)}" ${s===selected?'selected':''}>${esc(s)}</option>`).join('')}</select></div></div><div id="team-table">${teamTable(selected)}</div><div class="season-players"><div class="section-head"><div><h2>Jatekosok a szezonban</h2><p class="muted">A kiválasztott szezonban játszó játékosok</p></div><div class="profile-actions">${canEdit()?'<button class="secondary" id="add-season-player">Jatekos hozzaadasa</button>':''}</div></div><div id="active-season-players">${seasonPlayers(selected)}</div></div></section>`}
function playerRows(){return [...players].sort((a,b)=>(b.total_goals??b.totalGoals)-(a.total_goals??a.totalGoals)).map(p=>{let jersey=p.jersey_number??p.jerseyNumber??'';return `<tr class="clickable" data-player="${esc(p.id)}"><td><strong>${esc(p.name)}</strong></td><td>${jersey||' '}</td><td>${p.league_apps??p.leagueApps??0}</td><td>${p.cup_apps??p.cupApps??0}</td><td>${p.league_goals??p.leagueGoals??0}</td><td>${p.cup_goals??p.cupGoals??0}</td><td><strong>${p.total_goals??p.totalGoals??0}</strong></td><td>${canEdit()?`<button class="edit-player" data-edit-player="${esc(p.id)}">Szerkeszt</button>`:''}</td></tr>`}).join('')}
function playersPage(){return `<section class="panel"><div class="section-head"><div><h2>Jatekosok</h2><p class="muted">Kattints egy jatekosra a szezonok es merkozesek megnyitasahoz.</p></div><div class="profile-actions"><span class="role">${players.length} jatekos</span>${canEdit()?'<button class="primary" id="add-player">Uj jatekos</button>':''}</div></div><div class="table-wrap"><table><thead><tr><th>Jatekos</th><th>Mez szam</th><th>Bajnoki megjelenes</th><th>Kupa megjelenes</th><th>Bajnoki gol/ok</th><th>Kupa gol/ok</th><th>Osszes gol</th><th></th></tr></thead><tbody>${playerRows()}</tbody></table></div></section>`}
function openPlayerProfile(id){const p=players.find(x=>x.id===id);if(!p)return;const rows=playerMatches.filter(x=>x.player_id===id||x.playerId===id),seasons=[...new Set(rows.map(x=>x.season).filter(Boolean))].sort().reverse();document.querySelector('#page-title').textContent=p.name;document.querySelector('#content').innerHTML=`<button class="back" id="back">← Jatekosok</button><section class="player-hero"><div><span class="eyebrow">Jatekos adatlap</span><h2>${esc(p.name)}</h2><p class="muted">Szezonok es merkozesenkenti adatok</p></div><div class="profile-actions">${canEdit()?'<button class="secondary" id="add-season">Szezon hozzaadasa</button><button class="primary" id="add-player-match">Merkozes hozzaadasa</button>':''}</div></section><section class="panel"><div class="section-head"><div><h2>Merkozesek nyilvantartasa</h2><p class="muted">Valassz egy szezont a jatekos merkozeseinek szuresehez.</p></div><select id="player-season"><option value="all">Minden szezon</option>${seasons.map(s=>`<option>${esc(s)}</option>`).join('')}</select></div><div id="history"></div></section>`;document.querySelector('#back').addEventListener('click',()=>show('players'));document.querySelector('#player-season').addEventListener('change',e=>history(rows,e.target.value));if(canEdit()){document.querySelector('#add-season').addEventListener('click',()=>addPlayerSeason(p));document.querySelector('#add-player-match').addEventListener('click',()=>addPlayerMatch(p,seasons))}history(rows,'all')}
function history(rows,season){let data=rows.filter(x=>season==='all'||x.season===season);document.querySelector('#history').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Szezon</th><th>Datum</th><th>Sorozat</th><th>Ellenfel</th><th>Allas</th><th>Eredmeny</th><th>Jatszott</th><th>Gol</th><th title="Yellow card">🟨</th><th title="One yellow and one red">🟨🟥</th><th title="Red card">🟥</th>${canEdit()?'<th></th>':''}</tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.season)}</td><td>${esc(x.match_date||x.matchDate||'')}</td><td>${esc(x.competition==='League'?'Bajnoksag':'Kupa')}</td><td>${esc(x.opponent)}</td><td>${esc(x.score||'')}</td><td><span class="result ${rc(x.result)}">${x.result==='U'?'?':x.result}</span></td><td>${x.played??1}</td><td>${x.goals??0}</td><td>${x.yellow_cards??x.yellowCards??x.stat1??0}</td><td>${x.yellow_red_cards??x.yellowRedCards??x.stat2??0}</td><td>${x.red_cards??x.redCards??x.stat3??0}</td>${canEdit()?`<td><button class="edit" data-stat="${esc(x.id)}">Szerkeszt</button></td>`:''}</tr>`).join('')||'<tr><td colspan="12" class="empty">Nincs merkozes ehhez a szezonhoz.</td></tr>'}</tbody></table></div>`;if(canEdit())document.querySelectorAll('[data-stat]').forEach(b=>b.addEventListener('click',()=>editPlayerMatch(rows.find(x=>String(x.id)===b.dataset.stat))))}
function show(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelector('#page-title').textContent=page==='dashboard'?'Tablazat':page==='players'?'Jatekosok':'Merkozesek';const c=document.querySelector('#content');if(page==='dashboard'){c.innerHTML=dashboard();bindSeasonPlayers();document.querySelector('#team-season').addEventListener('change',e=>{document.querySelector('#team-table').innerHTML=teamTable(e.target.value);document.querySelector('#active-season-players').innerHTML=seasonPlayers(e.target.value);bindSeasonPlayers();if(canEdit())bindSeasonPlayerButton(e.target.value)});if(canEdit()){document.querySelector('#add-season').addEventListener('click',addGlobalSeason);bindSeasonPlayerButton(document.querySelector('#team-season').value)}}else if(page==='players'){c.innerHTML=playersPage();document.querySelectorAll('.clickable').forEach(r=>r.addEventListener('click',e=>{if(e.target.closest('button'))return;openPlayerProfile(r.dataset.player)}));if(canEdit()){document.querySelector('#add-player').addEventListener('click',addPlayer);document.querySelectorAll('[data-edit-player]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();editPlayer(players.find(p=>p.id===b.dataset.editPlayer))}))}}else{c.innerHTML=`<section class="toolbar"><p class="muted">${matches.length} shared matches</p></section><div class="table-wrap"><table><thead><tr><th>Datum</th><th>Ellenfel</th><th>Sorozat</th><th>Allas</th><th>Eredmeny</th></tr></thead><tbody>${matches.map(m=>`<tr><td>${esc(m.match_date)}</td><td>${esc(m.opponent)}</td><td>${esc(m.competition==='League'?'Bajnoksag':'Kupa')}</td><td>${esc(m.score||'vs')}</td><td><span class="result ${rc(m.result)}">${esc(m.result||'Upcoming')}</span></td></tr>`).join('')}</tbody></table></div>`}}
function dialog(title,body,save){const d=document.createElement('dialog');d.innerHTML=`<form method="dialog" class="dialog-card"><h2>${title}</h2>${body}<div class="dialog-actions"><button value="cancel" class="ghost">Megse</button><button id="save" class="primary">Mentes</button></div></form>`;document.body.append(d);d.showModal();d.querySelector('#save').addEventListener('click',async e=>{e.preventDefault();await save(d)})}
function bindSeasonPlayerButton(season){const b=document.querySelector('#add-season-player');if(b)b.addEventListener('click',()=>addPlayerToSeason(season));}
async function addPlayerToSeason(season){const options=players.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join('');dialog('Jatekos hozzaadasa a szezonhoz','<p class="muted">Aktiv szezon: '+esc(season)+'</p><select id="player">'+options+'</select>',async d=>{const{error}=await supabase.from('player_seasons').upsert({player_id:d.querySelector('#player').value,season},{onConflict:'player_id,season'});if(error){alert(error.message);return}d.close();d.remove();await load();show('dashboard')})}
async function addGlobalSeason(){dialog('Uj szezon','<input id="season" placeholder="Pelda: 2026/2027" required><input id="note" placeholder="Megjegyzes, opcionális">',async d=>{let season=d.querySelector('#season').value.trim();if(!season)return;const{error}=await supabase.from('seasons').insert({season,notes:d.querySelector('#note').value});if(error){alert(error.message);return}d.close();d.remove();await load();show('dashboard')})}
async function addPlayerSeason(p){dialog('Szezon hozzaadasa','<input id="season" placeholder="Pelda: 2026/2027" required><input id="note" placeholder="Megjegyzes, opcionális">',async d=>{const{error}=await supabase.from('player_seasons').insert({player_id:p.id,season:d.querySelector('#season').value.trim(),notes:d.querySelector('#note').value});if(error){alert(error.message);return}d.close();d.remove();await load();openPlayerProfile(p.id)})}
async function addPlayer(){const seasons=seasonNames();dialog('Uj jatekos','<input id="name" placeholder="Jatekos neve" required><label>Mez szam<input id="jersey" type="number" min="0"></label><label>Aktiv szezon<select id="season">'+seasons.map(s=>'<option>'+esc(s)+'</option>').join('')+'</select></label><label>Bajnoki megjelenes<input id="la" type="number" min="0" value="0"></label><label>Kupa megjelenes<input id="ca" type="number" min="0" value="0"></label><label>Bajnoki gol/ok<input id="lg" type="number" min="0" value="0"></label><label>Kupa gol/ok<input id="cg" type="number" min="0" value="0"></label>',async d=>{const name=d.querySelector('#name').value.trim(),id=idFor(name),season=d.querySelector('#season').value;const{error}=await supabase.from('players').insert({id,name,jersey_number:+d.querySelector('#jersey').value||null,league_apps:+d.querySelector('#la').value,cup_apps:+d.querySelector('#ca').value,league_goals:+d.querySelector('#lg').value,cup_goals:+d.querySelector('#cg').value});if(error){alert(error.message);return}const{error:seasonError}=await supabase.from('player_seasons').upsert({player_id:id,season},{onConflict:'player_id,season'});if(seasonError){alert(seasonError.message);return}d.close();d.remove();await load();show('players')})}
async function editPlayer(p){dialog('Jatekos szerkesztese',`<input id="name" value="${esc(p.name)}" required><label>Mez szam<input id="jersey" type="number" min="0" value="${p.jersey_number??p.jerseyNumber??''}"></label><label>Bajnoki megjelenes<input id="la" type="number" min="0" value="${p.league_apps??p.leagueApps??0}"></label><label>Kupa megjelenes<input id="ca" type="number" min="0" value="${p.cup_apps??p.cupApps??0}"></label><label>Bajnoki gol/ok<input id="lg" type="number" min="0" value="${p.league_goals??p.leagueGoals??0}"></label><label>Kupa gol/ok<input id="cg" type="number" min="0" value="${p.cup_goals??p.cupGoals??0}"></label>`,async d=>{const{error}=await supabase.from('players').update({name:d.querySelector('#name').value,jersey_number:+d.querySelector('#jersey').value||null,league_apps:+d.querySelector('#la').value,cup_apps:+d.querySelector('#ca').value,league_goals:+d.querySelector('#lg').value,cup_goals:+d.querySelector('#cg').value}).eq('id',p.id);if(error){alert(error.message);return}d.close();d.remove();await load();show('players')})}
async function addPlayerMatch(p,seasons){dialog('Merkozes hozzaadasa',`<select id="season">${seasons.map(s=>`<option>${esc(s)}</option>`).join('')||'<option>2026/2027</option>'}</select><select id="comp"><option>League</option><option>Cup</option></select><input id="date" type="date"><input id="opp" placeholder="Ellenfel" required><input id="score" placeholder="Allas"><select id="result"><option>W</option><option>D</option><option>L</option><option>U</option></select><label>Gol<input id="goals" type="number" min="0" value="0"></label><label>🟨<input id="y" type="number" min="0" value="0"></label><label>🟨🟥<input id="yr" type="number" min="0" value="0"></label><label>🟥<input id="r" type="number" min="0" value="0"></label>`,async d=>{const{error}=await supabase.from('player_match_stats').insert({player_id:p.id,season:d.querySelector('#season').value,competition:d.querySelector('#comp').value,match_date:d.querySelector('#date').value||null,opponent:d.querySelector('#opp').value,score:d.querySelector('#score').value,result:d.querySelector('#result').value,played:1,goals:+d.querySelector('#goals').value,yellow_cards:+d.querySelector('#y').value,yellow_red_cards:+d.querySelector('#yr').value,red_cards:+d.querySelector('#r').value});if(error){alert(error.message);return}d.close();d.remove();await load();openPlayerProfile(p.id)})}
async function editPlayerMatch(m){dialog('Jatekos merkozes szerkesztese',`<input id="opp" value="${esc(m.opponent)}"><input id="score" value="${esc(m.score||'')}" placeholder="Allas"><select id="result"><option ${m.result==='W'?'selected':''}>W</option><option ${m.result==='D'?'selected':''}>D</option><option ${m.result==='L'?'selected':''}>L</option><option ${m.result==='U'?'selected':''}>U</option></select><label>Gol<input id="goals" type="number" value="${m.goals??0}"></label><label>🟨<input id="y" type="number" value="${m.yellow_cards??m.yellowCards??m.stat1??0}"></label><label>🟨🟥<input id="yr" type="number" value="${m.yellow_red_cards??m.yellowRedCards??m.stat2??0}"></label><label>🟥<input id="r" type="number" value="${m.red_cards??m.redCards??m.stat3??0}"></label>`,async d=>{const{error}=await supabase.from('player_match_stats').update({opponent:d.querySelector('#opp').value,score:d.querySelector('#score').value,result:d.querySelector('#result').value,goals:+d.querySelector('#goals').value,yellow_cards:+d.querySelector('#y').value,yellow_red_cards:+d.querySelector('#yr').value,red_cards:+d.querySelector('#r').value}).eq('id',m.id);if(error){alert(error.message);return}d.close();d.remove();await load();openPlayerProfile(m.player_id||m.playerId)})}
async function boot(){const{data}=await supabase.auth.getSession();session=data.session;if(!session){renderAuth();return}const{data:p}=await supabase.from('profiles').select('role').eq('id',session.user.id).single();profile=p||{role:'viewer'};await load();shell()}
supabase.auth.onAuthStateChange((_e,next)=>{session=next;if(next)boot();else renderAuth()});boot()
