create table if not exists public.player_seasons (id bigint generated by default as identity primary key, player_id text references public.players(id) on delete cascade, season text not null, notes text default '', created_at timestamptz not null default now(), unique(player_id, season));
alter table public.player_seasons enable row level security;
drop policy if exists "authenticated users can read player seasons" on public.player_seasons;
create policy "authenticated users can read player seasons" on public.player_seasons for select to authenticated using (true);
drop policy if exists "editors can write player seasons" on public.player_seasons;
create policy "editors can write player seasons" on public.player_seasons for all to authenticated using (public.is_editor()) with check (public.is_editor());
