-- Run once if these columns/tables are not already present.
alter table public.players add column if not exists jersey_number integer;
alter table public.player_match_stats add column if not exists yellow_cards integer not null default 0;
alter table public.player_match_stats add column if not exists yellow_red_cards integer not null default 0;
alter table public.player_match_stats add column if not exists red_cards integer not null default 0;
create table if not exists public.seasons (id bigint generated by default as identity primary key, season text unique not null, notes text default '', created_at timestamptz not null default now());
alter table public.seasons enable row level security;
drop policy if exists "authenticated users can read seasons" on public.seasons;
create policy "authenticated users can read seasons" on public.seasons for select to authenticated using (true);
drop policy if exists "editors can write seasons" on public.seasons;
create policy "editors can write seasons" on public.seasons for all to authenticated using (public.is_editor()) with check (public.is_editor());
