create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'viewer' check (role in ('viewer','editor')),
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_date date not null,
  opponent text not null,
  competition text not null check (competition in ('League','Cup')),
  score text,
  result text check (result in ('W','D','L','Upcoming')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id,email) values (new.id,new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_editor() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'editor');
$$;

alter table public.profiles enable row level security;
alter table public.matches enable row level security;
create policy "authenticated users can read profiles" on public.profiles for select to authenticated using (true);
create policy "authenticated users can read matches" on public.matches for select to authenticated using (true);
create policy "editors can insert matches" on public.matches for insert to authenticated with check (public.is_editor());
create policy "editors can update matches" on public.matches for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "editors can delete matches" on public.matches for delete to authenticated using (public.is_editor());

-- After signing up with alfredvenczel@yahoo.com, promote that account:
-- update public.profiles set role = 'editor' where email = 'alfredvenczel@yahoo.com';
