-- Run once in Supabase SQL Editor before using editable Csapatok.
-- Existing matches remain intact. The app derives missing season/home/away values from existing data.

alter table public.matches add column if not exists season text;
alter table public.matches add column if not exists home_team text;
alter table public.matches add column if not exists away_team text;
alter table public.matches add column if not exists goal_scorers text;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  season text not null,
  created_at timestamptz not null default now(),
  unique (name, season)
);

grant select on public.teams to anon;
grant select, insert, update, delete on public.teams to authenticated;
grant usage, select on sequence public.teams_id_seq to authenticated;

alter table public.teams enable row level security;
drop policy if exists "public can read teams" on public.teams;
create policy "public can read teams" on public.teams for select to anon, authenticated using (true);
drop policy if exists "editors can manage teams" on public.teams;
create policy "editors can manage teams" on public.teams for all to authenticated using (public.is_editor()) with check (public.is_editor());
