-- Run once in Supabase SQL Editor before using editable Csapatok.
-- Existing matches remain intact. The app derives missing season/home/away values from existing data.

alter table public.matches add column if not exists season text;
alter table public.matches add column if not exists home_team text;
alter table public.matches add column if not exists away_team text;
alter table public.matches add column if not exists goal_scorers text;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  season text not null,
  notes text default '',
  stage text not null default 'main',
  played integer,
  wins integer,
  draws integer,
  losses integer,
  goals_for integer,
  goals_against integer,
  points integer,
  created_at timestamptz not null default now(),
  unique (name, season, stage)
);

grant select on public.teams to anon;
grant select, insert, update, delete on public.teams to authenticated;
grant usage, select on sequence public.teams_id_seq to authenticated;

alter table public.teams add column if not exists notes text default '';
alter table public.teams add column if not exists stage text not null default 'main';
update public.teams set stage = 'main' where stage is null;

-- A team can exist once in the regular table and again in the Play out table for the same season.
alter table public.teams drop constraint if exists teams_name_season_key;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'teams_name_season_stage_key'
      and conrelid = 'public.teams'::regclass
  ) then
    alter table public.teams add constraint teams_name_season_stage_key unique (name, season, stage);
  end if;
end $$;
alter table public.teams add column if not exists played integer;
alter table public.teams add column if not exists wins integer;
alter table public.teams add column if not exists draws integer;
alter table public.teams add column if not exists losses integer;
alter table public.teams add column if not exists goals_for integer;
alter table public.teams add column if not exists goals_against integer;
alter table public.teams add column if not exists points integer;

alter table public.teams enable row level security;
drop policy if exists "public can read teams" on public.teams;
create policy "public can read teams" on public.teams for select to anon, authenticated using (true);
drop policy if exists "editors can manage teams" on public.teams;
create policy "editors can manage teams" on public.teams for all to authenticated using (public.is_editor()) with check (public.is_editor());
